require "conf.options"
require "conf.keymap"
require "conf.plugins"
require "conf.completion"
require "conf.lsp"
require "conf.nvimtree"
require "conf.devicons"
require "conf.treesitter"
require "conf.golang"
require "conf.neoclip"
require "conf.telescope"
require "conf.lualine"
require "conf.colorscheme"

