require "conf.options"
require "conf.keymap"
require "conf.plugins"
require "conf.colorscheme"
require "conf.completion"
require "conf.lsp"
require "conf.nvimtree"
require "conf.treesitter"
require "conf.golang"

